services:
  mongo1:
    image: mongo:7.0
    container_name: mongo1
    ports:
      - 27018:27017
    networks:
      - mongo-cluster
    volumes:
      - mongo1-data:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile
    command: ["bash", "-c", "chmod 400 /etc/mongo-keyfile && exec mongod --replSet rs0 --bind_ip_all --auth --keyFile /etc/mongo-keyfile"]

  mongo2:
    image: mongo:7.0
    container_name: mongo2
    ports:
      - 27019:27017
    networks:
      - mongo-cluster
    volumes:
      - mongo2-data:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile
    command: ["bash", "-c", "chmod 400 /etc/mongo-keyfile && exec mongod --replSet rs0 --bind_ip_all --auth --keyFile /etc/mongo-keyfile"]

  mongo3:
    image: mongo:7.0
    container_name: mongo3
    ports:
      - 27020:27017
    networks:
      - mongo-cluster
    volumes:
      - mongo3-data:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile
    command: ["bash", "-c", "chmod 400 /etc/mongo-keyfile && exec mongod --replSet rs0 --bind_ip_all --auth --keyFile /etc/mongo-keyfile"]

networks:
  mongo-cluster:
    driver: bridge

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:
